import json
import asyncio
from fastapi import FastAPI, HTTPException, Request
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import StreamingResponse
from pydantic import BaseModel
from langchain_core.messages import HumanMessage

# Import our database setup and compiled LangGraph agent
from .database import engine, Base, get_db 
from .agent.graph import crm_agent

from langchain_core.messages import HumanMessage


from .models import HCP, InteractionLog 
from sqlalchemy.orm import Session
from fastapi import Depends

# 1. Initialize Database Tables
# This automatically creates your Postgres tables if they don't exist yet
Base.metadata.create_all(bind=engine)

# 2. Initialize FastAPI App
app = FastAPI(
    title="AI-First CRM HCP Module",
    description="Backend for the LangGraph-powered life sciences CRM",
    version="1.0.0"
)

# 3. Configure CORS (Cross-Origin Resource Sharing)
# Crucial for allowing your React frontend (usually running on port 3000 or 5173) to talk to this API
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # In production, change this to ["http://localhost:3000"]
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# --- SCHEMAS ---

class ChatRequest(BaseModel):
    message: str
    thread_id: str = "default_session" # Used by LangGraph MemorySaver to remember the user

# --- STREAMING ENDPOINT ---

@app.post("/api/agent/stream")
async def chat_stream(request: ChatRequest):
    """
    Receives a message from the React UI and streams back the LangGraph agent's 
    thought process, tool executions, and final text response using Server-Sent Events (SSE).
    """
    if not request.message:
        raise HTTPException(status_code=400, detail="Message cannot be empty.")

    async def event_generator():
        try:
            # 1. Format the user's input for LangGraph
            input_state = {"messages": [HumanMessage(content=request.message)]}
            
            # 2. Configure the thread ID so the agent remembers conversation history
            config = {"configurable": {"thread_id": request.thread_id}}

            # 3. Stream the execution graph asynchronously
            # .astream() yields chunks of state as the graph moves from node to node
            async for event in crm_agent.astream(input_state, config=config, stream_mode="updates"):
                
                # event is a dictionary containing the node name and its output
                # Example: {'agent': {'messages': [...]}} or {'tools': {'messages': [...]}}
                for node_name, state_update in event.items():
                    
                    # We extract the latest message generated by this node
                    latest_message = state_update.get("messages", [])[-1]
                    
                    # Package the data to send to the React frontend
                    payload = {
                        "node": node_name,
                        "type": latest_message.type,
                        "content": latest_message.content,
                    }
                    
                    # If the agent decided to call a tool, we stream that intent
                    if hasattr(latest_message, 'tool_calls') and latest_message.tool_calls:
                        payload["tool_calls"] = latest_message.tool_calls

                    # SSE Format requires data to be prefixed with 'data: ' and end with '\n\n'
                    yield f"data: {json.dumps(payload)}\n\n"
                    
                    # Small sleep to yield control back to the event loop
                    await asyncio.sleep(0.01)

            # 4. Send a distinct termination event so the frontend knows to stop loading animations
            yield "data: {\"status\": \"[DONE]\"}\n\n"

        except Exception as e:
            error_payload = {"error": str(e)}
            yield f"data: {json.dumps(error_payload)}\n\n"

    # Return the generator wrapped in FastAPI's StreamingResponse
    return StreamingResponse(event_generator(), media_type="text/event-stream")


# --- HEALTH CHECK ENDPOINT ---

@app.get("/health")
def health_check():
    """Simple endpoint to verify the server is running."""
    return {"status": "healthy", "service": "crm-ai-backend"}


# --- FRONTEND DATA ENDPOINT ---

@app.get("/api/hcps/{hcp_id}")
def get_hcp_profile(hcp_id: int, db: Session = Depends(get_db)):
    """Fetches real-time HCP data and latest sentiment for the React frontend."""
    
    # 1. Query the database for the doctor
    hcp = db.query(HCP).filter(HCP.id == hcp_id).first()
    if not hcp:
        raise HTTPException(status_code=404, detail="HCP not found")
        
    # 2. Get their recent interactions to find the latest sentiment
    interactions = db.query(InteractionLog).filter(
        InteractionLog.hcp_id == hcp_id
    ).order_by(InteractionLog.interaction_date.desc()).all()
    
    # 3. Return the real data
    return {
        "id": hcp.id,
        "name": hcp.name,
        "specialty": hcp.specialty,
        "sentiment": interactions[0].sentiment if interactions else "Neutral",
        "recent_interactions": interactions
    }