from pydantic import BaseModel, Field, ConfigDict
from typing import List, Optional
from datetime import date
from enum import Enum

# --- 1. Strict Enums to prevent LLM hallucinations ---

class Sentiment(str, Enum):
    POSITIVE = "positive"
    NEUTRAL = "neutral"
    NEGATIVE = "negative"

class TaskStatus(str, Enum):
    PENDING = "pending"
    IN_PROGRESS = "in_progress"
    COMPLETED = "completed"
    CANCELED = "canceled"

# --- 2. Action Items (Follow-ups) ---

class ActionItemBase(BaseModel):
    task_description: str = Field(..., description="Clear, actionable description of the task to be completed.")
    due_date: Optional[date] = Field(None, description="ISO format date (YYYY-MM-DD) for when the task is due.")
    status: TaskStatus = Field(default=TaskStatus.PENDING)

class ActionItemCreate(ActionItemBase):
    """Schema expected when the LLM generates a new action item."""
    pass

class ActionItemResponse(ActionItemBase):
    """Schema for sending data to the React frontend."""
    id: int
    interaction_log_id: int
    model_config = ConfigDict(from_attributes=True)

# --- 3. Interaction Logs ---

class InteractionLogBase(BaseModel):
    interaction_date: date = Field(..., description="Date of the touchpoint (YYYY-MM-DD)")
    narrative_notes: str = Field(..., description="The raw notes or transcript of the interaction")
    topics: List[str] = Field(default_factory=list, description="List of key medical or business topics discussed")
    sentiment: Sentiment = Field(..., description="Overall sentiment of the interaction")
    summary: str = Field(..., description="A concise 2-3 sentence summary of the interaction")

class InteractionLogCreate(InteractionLogBase):
    """Schema for processing a new log. Can include nested action items generated by the LLM."""
    hcp_id: int
    new_action_items: Optional[List[ActionItemCreate]] = Field(
        default_factory=list, 
        description="Any new follow-up tasks generated from this interaction."
    )

class InteractionLogResponse(InteractionLogBase):
    """Schema for sending data to the React frontend."""
    id: int
    hcp_id: int
    action_items: List[ActionItemResponse] = []
    model_config = ConfigDict(from_attributes=True)

# --- 4. HCP Core Profiles ---

class HCPBase(BaseModel):
    name: str = Field(..., min_length=2, max_length=255)
    specialty: Optional[str] = Field(None, max_length=100)
    region: Optional[str] = Field(None, max_length=100)

class HCPResponse(HCPBase):
    """Schema for sending data to the React frontend."""
    id: int
    interaction_logs: List[InteractionLogResponse] = []
    model_config = ConfigDict(from_attributes=True)